name: whales
channels:
  - conda-forge
dependencies:
  - gdal
  - python>=3.11,<3.15
  - pip
  - pip:
    - -e .[dev]
    - bottle>=0.12
    - jupyter
    - mercantile>=1.2
    - pyarrow>=15.0.0  # to silence warning from Pandas, can be removed after pandas 3.0
    - requests
    - requests-auth>=0.6
